In [1]:
import numpy as np
import pandas as pd
from IPython.display import clear_output
from scipy.spatial import distance

# Feedforward

In [ ]:
# import Prototype matrix 

k = int(input('Number of Prototypes : '))
l = int(input('Size of Prototype matrix : '))

output_1 = FF(k,l)
print('Output of feedforward layer : \n',output_1)

In [ ]:
def FF(k,l):
    #Set variables
    
    W_1 = np.zeros((k,l))
    R = l
    b_1 = np.matrix([[R],[R]])
    
    
    #Weight
    
    for i in range(k):
        for j in range(l):
            W_1[i,j]=int(input(print((j+1),'number of ',(i+1),'prototype')))
            
    #Input data (p)
    
    p = np.zeros((1,l))
    for n in range(l):
        p[0,n] = int(input(print((n+1),'number of input.')))
        
        
    #First layer output
    
    a_1 = (np.inner(W_1,p))+b_1

In [2]:
# import Prototype matrix, weight, S, R, bias for first layer 


k = int(input('Number of Prototypes : '))
l = int(input('Size of Prototype matrix : '))
W_1 = np.zeros((k,l))
S = k
R = l
b_1 = np.matrix([[R],[R]])


for i in range(k):
    for j in range(l):
        W_1[i,j]=int(input(print((j+1),'number of ',(i+1),'prototype')))
        

#Input data (p)

p = np.zeros((1,l))

for n in range(l):
    p[0,n] = int(input(print((n+1),'number of input.')))

#First layer output

a_1 = (np.inner(W_1,p))+b_1

clear_output()
print('Output of feedforward layer : \n',a_1)

Output of feedforward layer : 
 [[4.]
 [2.]]


## Poslin function

In [4]:
def poslin(matrix):
    q,w = matrix.shape
    m_2 = np.array(matrix.reshape(1,(q*w)))
    m_2 = np.where(m_2<0,0,m_2)
    m_2 = m_2.reshape(q,w)
    m_2 = np.matrix(m_2)
    return(m_2)

# Recurrent layer

In [19]:
def iteration(a2_T):
    a2_T = a2_T.reshape((1,2))
    a2_Tp1 = poslin(np.inner(W_2,a2_T))
    return(a2_Tp1)

In [22]:
# Set weight for Recurrent layer
S = k
eps = S
while(eps>(1/(S-1))):
    eps = float(input(print('Insert an epsilon less than',(1/(S-1)))))

    
W_2 = np.matrix([[1 ,-(eps)],
                 [-(eps) ,1]])


a_2p = np.zeros((1,2))
a_2 = a_1
while(np.any(np.not_equal(a_2p,a_2))):
    a_2p = a_2
    a_2 = iteration(a_2p)
    print('New a_2 is : \n ',a_2)

Insert an epsilon less than 1.0
None.5
New a_2 is : 
  [[3.]
 [0.]]
New a_2 is : 
  [[3.]
 [0.]]


# Output

In [29]:
q,w = W_1.shape

for i in range(q):
    

IndexError: list assignment index out of range

In [52]:
distance.hamming([0,3], [-1, -1])

1.0

In [ ]:
dis