In [1]:
import numpy as np
import pandas as pd
from IPython.display import clear_output
from scipy.spatial import distance

# Feedforward

In [2]:
def Set(k,l):
    
    #Set variables
    W_1 = np.zeros((k,l))
    
    
    #Weight
    for i in range(k):
        for j in range(l):
            W_1[i,j]=int(input(print((j+1),'number of ',(i+1),'prototype')))
            
            
    #Input data (p)
    p = np.zeros((1,l))
    for n in range(l):
        p[0,n] = int(input(print((n+1),'number of input.')))
        
    return(p,W_1)

In [3]:
def FF(p,W_1,R):
    #First layer output
    
    b_1 = np.matrix([[R],[R]])
    a_1 = (np.inner(W_1,p))+b_1
    
    return(a_1)

In [4]:
# import Prototype matrix 

k = int(input('Number of Prototypes : '))
l = int(input('Size of Prototype matrix : '))

Input,Weight_1 = Set(k,l)

output_1 = FF(Input,Weight_1,l)

clear_output()
print('Output of feedforward layer : \n',output_1)

Output of feedforward layer : 
 [[4.]
 [2.]]


## Poslin function

In [5]:
def poslin(matrix):
    q,w = matrix.shape
    m_2 = np.array(matrix.reshape(1,(q*w)))
    m_2 = np.where(m_2<0,0,m_2)
    m_2 = m_2.reshape(q,w)
    m_2 = np.matrix(m_2)
    return(m_2)

# Recurrent layer

## Iteration

In [6]:
def iteration(a2_T,W_2):
    a2_T = a2_T.reshape((1,2))
    a2_Tp1 = poslin(np.inner(W_2,a2_T))
    return(a2_Tp1)

In [7]:
def BW(output_1,S):
    
    eps = S
    
    while(eps>(1/(S-1))):
        eps = float(input(print('Insert an epsilon less than',(1/(S-1)))))
        clear_output()

    
    W_2 = np.matrix([[1 ,-(eps)],
                     [-(eps) ,1]])
    
    a_2p = np.zeros((1,2))
    a_2 = output_1
    
    while(np.any(np.not_equal(a_2p,a_2))):
        a_2p = a_2
        a_2 = iteration(a_2p,W_2)
        print('New a_2 is : \n ',a_2)
        
    return(a_2)

In [8]:
# Set weight for Recurrent layer
output_2 = BW(output_1,k)

New a_2 is : 
  [[3.]
 [0.]]
New a_2 is : 
  [[3.]
 [0.]]


# Output

In [ ]:
#Calculate Prototype variable

d={}
for z in range(k):
    p = Weight_1[z].reshape((1,3))
    O_1 = FF(p,Weight_1,l)
    O_2 = BW(O_1,k)

    
    
    d["P{0}".format(z)] = O_2
    

In [29]:
#Find Input class

HD_pre = 999
j = None
for i in range(k):
    
    print('\n Hamming distance Between Class ',(i+1),' and input \n')
    HD = distance.hamming(d["P{0}".format(i)],output_2)
    print(HD)
    
    
    if(HD<HD_pre):
        HD_pre = HD
        j = i
    
    
print('\n ***************** \n')
print(Input,' is your Input data. \n')
print('From ',(j+1),' class. \n')
print('With hamming distance : ',HD_pre)


 Hamming distance Between Class  1  and input 

0.5

 Hamming distance Between Class  2  and input 

1.0

 ***************** 

[[-1. -1. -1.]]  is your Input data. 

From  1  class. 

With hamming distance :  0.5
